sudo: required

services:
  - docker

install: true
script:
  - echo 'Build script folded...' && echo -en 'travis_fold:start:build\\r'
  - ./build.sh
  - echo -en 'travis_fold:end:build\\r'
deploy:
  provider: script
  script: bash push.sh
  on:
    branch: master
    condition: -z "${TRAVIS_ART1_DOCKER_REG_PASSWORD}"
