sudo: required

services:
  - docker

install: true
script: ./build.sh
deploy:
  provider: script
  script: bash push.sh
  on:
    branch: master
    condition: -z "${TRAVIS_ART1_DOCKER_REG_PASSWORD}"
    condition: -z "${TRAVIS_ART1_DOCKER_REG}"